INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, RATE_EXCHANGE) VALUES (1001, 'USD', 'CFA', 609.00); 
INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, RATE_EXCHANGE) VALUES (1002, 'EUR', 'CFA', 660.67); 
INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, RATE_EXCHANGE) VALUES (1003, 'DIRHAM', 'CFA', 59.82); 
INSERT INTO CURRENCY_EXCHANGE (ID, CURRENCY_FROM, CURRENCY_TO, RATE_EXCHANGE) VALUES (1004, 'NAIRA', 'CFA', 1.35);