INSERT INTO USER_AUTHENTIFICATION (ID, USER_LOGIN, USER_PASSWORD) VALUES (1001, 'NABOU', 'PASSER1'); 
INSERT INTO USER_AUTHENTIFICATION (ID, USER_LOGIN, USER_PASSWORD) VALUES (1002, 'MAYRA', 'PASSER2'); 
INSERT INTO USER_AUTHENTIFICATION (ID, USER_LOGIN, USER_PASSWORD) VALUES (1003, 'MOUHAMED', 'PASSER3'); 
INSERT INTO USER_AUTHENTIFICATION (ID, USER_LOGIN, USER_PASSWORD) VALUES (1004, 'OUZE', 'PASSER4');